(dp1
S'output'
p2
S'<type \'exceptions.SyntaxError\'> Field: invalid table name: Work Out, use rname for "funny" names'
p3
sS'layer'
p4
S'/Users/subash/Dropbox/MTechSem1/1_ScriptingAndComputingEnv/web2py/applications/iConnect/models/db1.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\n# Interests\n\ndb.define_table('Travelling',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Movies',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Music',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Fitness',\n\tField('userId','reference auth_user')\n\t)\n\n#Hobbies\n\ndb.define_table('Singing',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Dancing',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Photography',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Painting',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Reading',\n\tField('userId','reference auth_user')\n\t)\n\n#Cuisine\n\ndb.define_table('Chinese',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('SouthIndian',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Continental',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Italian',\n\tField('userId','reference auth_user')\n\t)\n\n#Sports/Fitness\n\ndb.define_table('Running',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Swimming',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Badminton',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Cricket',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Basketball',\n\tField('userId','reference auth_user')\n\t)\n\ndb.define_table('Work Out',\n\tField('userId','reference auth_user')\n\t)\n\n\n\n\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/subash/Dropbox/MTechSem1/1_ScriptingAndComputingEnv/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/Users/subash/Dropbox/MTechSem1/1_ScriptingAndComputingEnv/web2py/applications/iConnect/models/db1.py", line 83, in <module>\n    Field(\'userId\',\'reference auth_user\')\n  File "/Users/subash/Dropbox/MTechSem1/1_ScriptingAndComputingEnv/web2py/gluon/packages/dal/pydal/base.py", line 819, in define_table\n    table = self.lazy_define_table(tablename,*fields,**args)\n  File "/Users/subash/Dropbox/MTechSem1/1_ScriptingAndComputingEnv/web2py/gluon/packages/dal/pydal/base.py", line 836, in lazy_define_table\n    table = table_class(self, tablename, *fields, **args)\n  File "/Users/subash/Dropbox/MTechSem1/1_ScriptingAndComputingEnv/web2py/gluon/packages/dal/pydal/objects.py", line 226, in __init__\n    \'use rname for "funny" names\' % tablename)\nSyntaxError: Field: invalid table name: Work Out, use rname for "funny" names\n'
p11
s.